services:
  mysql:
    image: mysql:8.0
    container_name: mysql-loja
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 3e4e5e6
      MYSQL_DATABASE: loja_e_commerce
      MYSQL_USER: loja_user
      MYSQL_PASSWORD: 3e4e5e6
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - private_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p3e4e5e6"]
      interval: 10s
      timeout: 5s
      retries: 5

  loja-backend:
    image: loja-backend
    container_name: loja-backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/loja_e_commerce?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 3e4e5e6
      JWT_SECRET: 12345678
      JWT_ISSUER: "API LOJA"
    ports:
      - "8080:8080"
    networks:
      - private_network
      - public_network
    restart: always

  loja-frontend:
    build:
      context: ../loja-frontend
      dockerfile: Dockerfile
    container_name: loja-frontend
    depends_on:
      - loja-backend
    ports:
      - "4200:80"
    networks:
      - public_network
volumes:
  mysql_data:

networks:
  private_network:
    driver: bridge
  public_network:
    driver: bridge
